spring:
  datasource:
    url: jdbc:mysql://localhost:3306/elementary_school_management_system
    username: root
    password: "#Akosijomer02"
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
devtools:
  add-properties: false
logging:
  level:
    org.springframework: info

application:
  security:
    jwt:
      secretKey: ec8f63b5685486211ef07fb0c9110df80e56df7ffc60b81f8b0c5d376226a44e
      expirationMs: 20000
      refreshExpirationMs: 60000

#  ZWxlbWVudGFyeXNjaG9vbG1hbmFnZW1lbnRzeXN0ZW0=